### ISSUE TITLE
BB3 Worksheets - page 38

### ISSUE THREAD

**Issue by rryman** [rryman/BB3-Worksheets#11]
Rhonda:
Should we add a note below the title on p. 38? Suggestion:
Note that the movement line inadvertently omitted in the eBook/ebook p. 50 from the behind sign for the right hand on Bar 1 count 4 has been included in the notation on pp. 38-39.

Robyn:
I am fine with this if you think it is necessary.
Let's use lower case for ebook throughout.

**Comment by rsryman** [comment]
There is only one other usage of "ebook" (p. 14). Done.

On p. 38 I decided to say _Book 3_ instead. See changes in highlighted below in bold below, OK?

Note that the _movement_ line inadvertently omitted in **_Book 3_ on the _behind_ sign for the right hand, Bar 1 count 4,** has been included in the notation on pp. 38-39.
