### ISSUE TITLE
BB3 Worksheets - Page 52 (Book 3 p. 65)

### ISSUE THREAD

**Issue by rryman** [rryman/BB3-Worksheets#16]
Can we incorporate pages 51 and 52 (exercise from Book 3 p. 65)?

This is what you said you would take some time on your own to think about.

Could we say on page 51:
In stave 1, add _repeat_ sign markings to make the arms repeat on the other side and the legs repeat in reverse.
In stave 3, add _repeat_ sign markings to make Bars 1-2 repeat in reverse, using _reverse repeat_ signs with the arm positions clarified in the empty bars as needed.
In the empty staves 5-6 below, fully notate the sequence without using repeat signs.

Then delete page 52?

**Comment by rsryman** [comment]
Done, OK?

**Comment by rryman** [comment]
As well as the repeat sign markings, I will be taking out the arms in the 'empty' bar in the second example, so would it be more helpful to say something like ...

In stave 3, add _repeat_ sign markings to make Bars 1-2 repeat in reverse, using _reverse repeat_ signs. Also notate the arm and head movements in the first ‘empty’ bar to clarify that they repeat on the other side.

Please feel free to wordsmith it.

**Comment by rsryman** [comment]
I wondered about this but thought it might require complicated instructions. Your comments address this simply and clearly. Done.
