### ISSUE TITLE
Global Instructions

### ISSUE THREAD

**Issue by rryman** [rryman/BB3-Worksheets#19]
Do you think it is worth putting a global instruction in BB3 Worksheets like you did in BB2 Worksheets so the instructions throughout BB3 Worksheets can be simplified?

"When grey notation is provided, trace the Benesh signs (not the bar lines and stave lines). Then copy each series of frames in the space provided below it, paying careful attention to sign proportions and to the placement of signs in relation to the centre of each frame."

That would mean going back through BB3 Worksheets and taking out the copying instructions each time they changed and we reiterated what the student should do.

Whatever you think is simplest for the students and the layout. I know Canan didn't like repeated instructions, but when things keep changing it seems clearer to say so (unless there is a global instruction in the beginning that makes it clear).

**Comment by rryman** [comment]
I took a look through BB3 Worksheets again and I think they are fine as is without a global instruction. We are asking different things so often, that in these worksheets it is probably good to clarify the instructions each time. If Canan (or her students) have an issue with it, we can update it if necessary.

**Comment by rsryman** [comment]
OK, let's leave this for now.
