### ISSUE TITLE
ConsistentFormat

### ISSUE THREAD

**Issue by rsryman** [rryman/BB3-Worksheets#2]
√Add updated Acknowledgements
See Github Issue BB1 Issue#3:
√1. Use consistent format for the section title: 
**Positions of the Feet** (_Book 1_ Summary p. #/pp. #). 
√2. Place each label above the corresponding BMN clip, followed by a colon only if there is more info, e.g. 1st: flat/demi-pointes/pointes. See BB3 Worksheets p. 4 as a model.
√3. Try to keep font size consistent
√4. Add solid start/end stave bar line (instead of dashed bar line)
√5. Use superscript re 1st/2nd/3rd/4th/5th
√6. Add/update "TM" on p. 2, as in BB1 Worksheets (Option+2)

**Inconsistencies re BB2Worksheets:**
p. 16 Delete Ex. 1/2/3 (over - end bracket missing  GLOBAL SEARCH RE:
√1. "Ex." (delete) and try to make font size consistent if possible name in 12pt??, sub-label in 10pt??
√2. Placement of "continued" after title/before page reference, e.g., BB2 Worksheet p. 7: **Movement Lines** continued (_Book 2_ p. 13)

Updated pdf (**Still To Do with Robyn: go through text to eliminate redundant instructions**):
[BB3WorksheetsAug27.pdf](https://github.com/rryman/BB3-Worksheets/files/2325620/BB3WorksheetsAug27.pdf)

**Comment by rsryman** [comment]
Updates made Sept 9, 2018:
[BB3WorksheetsSept9,2018.pdf](https://github.com/rryman/BB3-Worksheets/files/2364523/BB3WorksheetsSept9.2018.pdf)

-changed footer to October 2018
-updated superscript re 1st/2nd/3rd/4th/5th
-removed colons after labels above BMN
-checked for consistent use of cap on initial word only re ballet terms (but NOT re names of exercises in **bold**)
-changed iBook to eBook on p.13
-updated all staves on p.61 (replaced dotted end bar with solid bar lines)

**Comment by rryman** [comment]
-changed footer to October 2018

Why did you italicize _copyright_ in the footer? It isn't italicized in BB1 or BB2 worksheets.

**Comment by rryman** [comment]
Page 4:

Suggestion: use the wording you did in BB2 worksheets ...

Neatness is important. Although the ultimate goal is to write the notation freehand, you may use
a ruler to draw Benesh signs where necessary until you master them.

Also add ...
Neatness is important. Although the ultimate goal is to write the notation freehand, you may use a ruler to draw Benesh signs where necessary until you master them. **Use a ruler to draw all bar lines.**

**Comment by rryman** [comment]
Page 5:

Use same format as BB1 page 13? I personally think it is clearer.
4th opposite 5th (and 4th Russian)

Error:
Bottom left-hand text under 4th opposite 5th (and 4th Russian) should be:
L ft bk, R ft fr

**Comment by rryman** [comment]
Page 6:

Use same format as BB2 Workheets, e.g.?
Sauté (English, Italian), Temps levé (Russian)

**Dégagé, Pointe tendue (Italian)**

**Comment by rryman** [comment]
Page 8:

Rise/Press-up - forward slash is okay here as we use that in the book.

**Comment by rryman** [comment]
Page 9:

Fix "th" on 5th:
Battements tendus closing/“drawing” into **5th** on demi-pointes and full pointes

**Comment by rryman** [comment]
Page 10 - I think keep it consistent with worksheets ... what do you think?

Consistent with worksheets - 
retiré devant/pirouette position (English)

Consistent with ebook - 
retiré devant/pirouette position, English

**Comment by rryman** [comment]
Page 11 - notation error

Last example: 
Bar 1 Count 1 - should be developpe
Bar 2 Count 3 - should be battement

**Comment by rryman** [comment]
Page 9 versus page 13:

OPTIONAL: An extra empty stave is provided below for you to re-write the sequence on the other side.

This text is 10 point on page 9 and 12 point on page 13. Is this because of a spacing issue on page 9?

**Comment by rryman** [comment]
RHONDA: Please confirm. By "same format" I thought you wanted me to use LB, RB above the BMN, and add the "key": LB=left foot behind, etc. This applies to pp. 4-5, and saves a line for each set. If so, should we repeat the key at the top of p. 5 and add LF, RF re the 4th position labels?
OR did you only mean "same format" re the wording: 4th opposite 5th (and 4th Russian) ??

ROBYN: Yes, I meant same format re - 4th opposite 5th (and 4th Russian).

**Comment by rryman** [comment]
RHONDA: Yes, this would add a line and change the spacing of p. 9. I could use 12 pt if I deleted the para break before "OPTIONAL" or decreased space between titles, staves. Preference?

ROBYN: Decrease space between titles and staves, between staves, between the two exercises, and the bottom example can be a bit close to the footer. Average it out ... a little bit from each space so it won't look like anything is too close to something else.

**Comment by rryman** [comment]
Should I work with your updated file when I get back to proofreading? If so, can you attach it here to GitHub?

**Comment by rsryman** [comment]
See p. 9 updated in:
[BB3WorksheetsSept12,2018.pdf](https://github.com/rryman/BB3-Worksheets/files/2376894/BB3WorksheetsSept12.2018.pdf)
