### ISSUE TITLE
More on Reverse Repeats (Book 3 p. 64) - BB3 Worksheets page 50

### ISSUE THREAD

**Issue by rryman** [rryman/BB3-Worksheets#20]
Canan pointed out a missing forward qualification sign at the beginning of the last two staves (when the arms go from en bas to arabesque. Do you think we should add them in the worksheets? If so, I should also make a note to update the ebook.

**Comment by rsryman** [comment]
I thought I had written to her to explain that the qualification is not needed to this "low" arabesque line.

**Comment by rryman** [comment]
Okay. Fine with me.
