### ISSUE TITLE
Tempos - Italic or Not

### ISSUE THREAD

**Issue by rryman** [rryman/BB3-Worksheets#21]
I noticed that we have been inconsistent in Book 2 in terms of italicizing the tempos.
We were inconsistent in Book 2 Worksheets - sometimes italicized and sometimes not.

In Book 3 we seem to consistently use "unitalicized" tempos.
Book 3 Worksheets p. 26 seems to be the only page we use italicized tempos.
Do you want me to "unitalicize" Allegro on these pages to be consistent throughout the worksheets?

Or do you want me to italicize them all given that the Benesh Encyclopedia, the RAD Set Exercises and Variations, and Eliane's book all use italicized tempos? However, the Parker book uses "unitalicized" text.

**Comment by rsryman** [comment]
This seems to be a stylistic choice. I searched the Encyclopaedia for "tempo," time signature," and "music" but could find no resources. I'd be happy to unitalicize what you found on p. 26 and leave the rest unitalicized, OK?

**Comment by rryman** [comment]
Okay. This works for me.

**Comment by rryman** [comment]
I'll leave this thread open until I get to p. 26.
