### ISSUE TITLE
Proofreading - Worksheet pages 1-8

### ISSUE THREAD

**Issue by rryman** [rryman/BB3-Worksheets#22]
- [x] p. 4: Printed on my laserprinter, the two-feet-together-level sign for 1st position demi-pointes sign is hard to see, although the 2nd position demi-pointes is crystal clear.

- [x] p. 5: See top line: RB =r ight foot behind -> RB = right foot behind
The two-feet-together-level signs re 5th LB & RB demi-pointes are hard to distinguish
The two-feet-together-level signs re closing 5th are clear on p. 7, so use the same thickness?

- [x] p. 6 Battement tendus closing into 5th position flat ->
Add "s" to Battement": Battements tendus closing into 5th position flat

**Comment by rryman** [comment]
I have implemented the corrections above. I went through and consistently changed the two feet together signs to .75 pt. For whatever reason, some are .6 pt and some are .71 pt.
I'll have to remember to change them on all the pages in Book 3.
Unfortunately, there is lots of inconsistency with signs and line thicknesses. It seems to depend on how the clip is imported into Word. If it is shrunk at all, this changes the signs and line sizes. 

Please check the implementation of the above corrections in the updated file attached.

[BB3Worksheets15JanP8.pdf](https://github.com/rryman/BB3-Worksheets/files/2760515/BB3Worksheets15JanP8.pdf)

Please close this issue if you are happy with the first 8 pages.

**Comment by rsryman** [comment]
Grrrr, round off error. 

Maybe you don’t need to check the line thickness of all level signs. It's most important to make them consistently .75 pt only when superimposed on a stave line, e.g.,  demi-pointes.

**Comment by rsryman** [comment]
Robyn's update (BB3Worksheets15JanP8.pdf) checked and MacBenesh file pp.5-6 updated.
