### ISSUE TITLE
Page 15 Updated

### ISSUE THREAD

**Issue by rryman** [rryman/BB3-Worksheets#23]
- [x] Rhonda, please look at the attached "BB3WorksheetsP15New.pdf" and compare it to the original page attached "BB3WorksheetsP15Old.pdf". I found the original page confusing because in Book 3 P19, there is no version given for the in-stave movement lines for this example. Also it is titled "Between-Frame Movement Lines" and there are no between-frame movement lines in this example.

If you agree with the update please tick and close this issue. If you do not agree, please let me know and I will change it.

[BB3WorksheetsP15New.pdf](https://github.com/rryman/BB3-Worksheets/files/2769458/BB3WorksheetsP15New.pdf)
[BB3WorksheetsP15Old.pdf](https://github.com/rryman/BB3-Worksheets/files/2769459/BB3WorksheetsP15Old.pdf)

**Comment by rsryman** [comment]
What about:
"The previous example, shown with between-frame movement lines devant and derrière, is rewritten below with in-frame movement lines devant and derrière. Note that an in-frame movement line is always used to show battement glissé/dégagé/jeté to the side."
Also, please check the height/placdement of the left foot level sign in Bar 1 count 3. It appears superimposed on the knees line in Bar 1 but shows up fine in Bar 2 count 3.

**Comment by rryman** [comment]
I have updated the text. I checked all the superimposed level signs and they are all the same line thickness. They all show up the same on my screen and when I print them out. Not sure what you want me to do about this. Do you want me to make them all thicker still?

[BB3WorksheetsP15.pdf](https://github.com/rryman/BB3-Worksheets/files/2774296/BB3WorksheetsP15.pdf)
