### ISSUE TITLE
Page 16 - Updated

### ISSUE THREAD

**Issue by rryman** [rryman/BB3-Worksheets#24]
- [x] Rhonda, please look at the attached "BB3WorksheetsP16New.pdf" and compare it to the original page attached "BB3WorksheetsP16Old.pdf". There was no title on this page, which is inconsistent as you always provide a page number in the book to which it refers. To fit the title in, I had to play with the layout of the page. I took out the extra stave to allow for more space and changed the instructions, as I like the idea that the students should try to write these examples on the other side as the cloche lines can be confusing and writing them on the other side will test their understanding of the theory.

If you agree with the update please tick and close this issue. If you do not agree, please let me know and I will change it.

[BB3WorksheetsP16New.pdf](https://github.com/rryman/BB3-Worksheets/files/2769636/BB3WorksheetsP16New.pdf)
[BB3WorksheetsP16Old.pdf](https://github.com/rryman/BB3-Worksheets/files/2769637/BB3WorksheetsP16Old.pdf)

**Comment by rsryman** [comment]
This compromise is a good solution.
