### ISSUE TITLE
Notation Reduced in Size

### ISSUE THREAD

**Issue by rryman** [rryman/BB3-Worksheets#26]
Rhonda, from page 17 onward, it looks as if the notation is reduced by 117%. This changes the distance between stave lines, line thicknesses, and sign sizes.

Please compare these two files.
BB3WorksheetsP17Old.pdf is your original document.
BB3WorksheetsP17New.pdf is my edited version. Notation scaled up by 120% and line thicknesses edited to match previous notation examples is Book 3.

As per our phone call, you are going to export Plie in 1st and 2nd (with Rise) from Book 3 p. 22 in postscript format and send the file to me. I am then going to paste it into the pdf of BB3Worksheets and see if this process fixes the issue.

[BB3WorksheetsP17Old.pdf](https://github.com/rryman/BB3-Worksheets/files/2775746/BB3WorksheetsP17Old.pdf)
[BB3WorksheetsP17New.pdf](https://github.com/rryman/BB3-Worksheets/files/2775747/BB3WorksheetsP17New.pdf)

**Comment by rryman** [comment]
I was just looking at Book 2 Worksheets and this was not a problem (see BB2 Worksheets pages 39 onward). Did you do something different for BB3 MacBenesh examples than you did for BB2 MacBenesh examples? It seems strange that it worked okay for BB2 but not for BB3?

**Comment by rsryman** [comment]
Yes your new version is clearer. Github doesn't support .ps from MacBenesh so I'll email that file to you.

I have attached the .pdf file from MacBenesh for your exploration.
[Plié1st2nd.pdf](https://github.com/rryman/BB3-Worksheets/files/2775780/Plie1st2nd.pdf)

**Comment by rryman** [comment]
Some good news. I have been opening each page of the BB3 Worksheets to check on the size of the notation examples.

Reduced examples are on pages: 18, 19 (first example only), 20, and 21.

So far the examples on the following pages are not reduced: 22, 23, 24, 25, and 26.

For whatever reason, not all of the notation examples are reduced! So you will only need export the ones that are reduced.

In the meantime, I will experiment with the file you sent me via email to see if this fix works for the examples that are reduced. If it does, perhaps I can make a list of the names of the reduced examples?

**Comment by rryman** [comment]
I used the Plié1st2nd.ps file successfully.

Here is a list of the other reduced examples I have found:
- [ ] Plié in 5th and 4th (Book 3 p. 23)
- [ ] Battement Tendu in 8 Directions of the Body, Italian (Book 3 p. 24)
- [ ] Adage (Book 3 p. 26): two alternate ways to notate this sequence
- [ ] Pirouette en Dehors from 4th and 5th, English (Book 3 p. 27)
- [ ] Tour en Dedans and en Dehors from 4th, Russian (Book 3 p. 28)
- [ ] Sissonne Ordinaire and Échappé Sauté (Book 3 p. 70) 

I went through the whole document using Preview and these are the only examples that appear to be a problem. If I encounter any others as I am editing each page with Adobe Illustrator I will let you know.

**Comment by rsryman** [comment]
Yes, good news that you can use the .ps files.

Here are the .ps files you requested. Let me know if there is anything else
you need.

**Comment by rryman** [comment]
Where are the .ps files?

**Comment by rsryman** [comment]
I attached them as a zip archive. Let me know if I need to upload them to Dropbox.

**Comment by rryman** [comment]
Where is the zip file? Did you put it on GitHub? If so, can you see it?
