### ISSUE TITLE
Format change on page 18

### ISSUE THREAD

**Issue by rryman** [rryman/BB3-Worksheets#27]
Rhonda, do you think it will be too confusing for students if I move the Grand Battement example from page 19 to page 18? There is more room on this page and it gives page 19 a much cleaner layout.
What do you think?

[BB3WorksheetsP18.pdf](https://github.com/rryman/BB3-Worksheets/files/2776768/BB3WorksheetsP18.pdf)

**Comment by rsryman** [comment]
Bettement Tendu and Grand Battement do fit on p. 19. Personally, I'd rather leave the worksheets in the same order as the ebook where possible, but I'll defer to your preference.

**Comment by rsryman** [comment]
OK, I understand. Let's go with your suggested reformatting of p. 18, with the added sentence.
