### ISSUE TITLE
Page 20 formatting issue

### ISSUE THREAD

**Issue by rryman** [rryman/BB3-Worksheets#28]
Due to the correctly sized notation for the two examples of the Adage, I can not fit 8 staves spaced with enough room for above and below information.

I can think of three choices:
1. I cheat by using some of the top margin (see attached). I think this maybe still a bit crowded for the students to notate the above and below stave information.
2. I create two pages for this example (in which case the students won't be able to see the difference on the one page and this will change the pagination of the rest of the document).
3. We show both examples on this page and ask the student to choose one of them to copy.

Which of these options do you prefer? Or is there another option?

The attached version has a smaller top margin (option 1. above)
[BB3WorksheetsP20.pdf](https://github.com/rryman/BB3-Worksheets/files/2776841/BB3WorksheetsP20.pdf)

**Comment by rryman** [comment]
Adding to the note above:
As I was working on page 21 I noticed this at the top of the page:
"OPTIONAL: Use a page of red-lined stave paper to rewrite either version of the Adage (p. 17) on the other side."

So what about taking this note out of page 21 and putting it on page 20 instead, i.e.,
give the two alternate versions of the Adage and ask them to rewrite either version of the Adage on the other side on the empty staves below? That way (on page 20) I can keep the same top margin and just leave two empty staves at the bottom of the page.

**Comment by rsryman** [comment]
I like the way you have solved the problem in BB3WorksheetsP20.pdf: 2 versions on same page for comparison, then a note on p. 21, but correct the page number (bolded below): 

OPTIONAL: Use a page of red-lined stave paper to rewrite either version of the Adage (p. **20**) on the other side.

**Comment by rryman** [comment]
I'd like to discuss this via phone call. I am going out now, but perhaps we can set a time to touch base tomorrow?

**Comment by rryman** [comment]
As per our phone call, I have updated page 20.
I had to decrease the font from 12pt to 11 pt for the text so that both would fit on one line.
Do you have a problem with this inconsistency?
Do you think this page is now okay?
If so, please close this issue.
If not, please let me know what needs to be changed.

[BB3WorksheetsP20.pdf](https://github.com/rryman/BB3-Worksheets/files/2784725/BB3WorksheetsP20.pdf)

**Comment by rsryman** [comment]
All good.
