### ISSUE TITLE
Page 26 - edit

### ISSUE THREAD

**Issue by rryman** [rryman/BB3-Worksheets#31]
- [x] Question re p. 26: Rhonda agrees that students need to recopy the in-stave notation for the first 2 sequences because the feet change on the beaten jump, but perhaps rather than copying the same thing again, we should provide in-stave notation minus repeat signs and add instructions (if there is room?): Recopy the "same side" and "other side" examples in the empty staves below, then add "alternate sides" repeat signs to the bottom stave.

**Comment by rryman** [comment]
What about the following?

- [ ] Recopy the "same side" and "other side" examples in the empty staves below, then add _repeat_
signs and relevant information to the bottom stave to show that the sequence is performed
four times in all **alternating** sides.

See attached pdf.

[BB3WorksheetsP26.pdf](https://github.com/rryman/BB3-Worksheets/files/2800206/BB3WorksheetsP26.pdf)

**Comment by rsryman** [comment]
This is a theory comprehension question (as well as a writing exercise) that would require the students to check their answer against _Book 3_ p. 39. Have we done this anywhere else? Is there room for a 6th stave with the alternating sides version?

**Comment by rryman** [comment]
Rhonda fine with leaving page 26 to the way I changed it.
I just have to change "recopy" to "copy".

**Comment by rryman** [comment]
Rhonda, I forgot to ask if you are okay with this rewording of the text?

Copy the "same side" and "other side" examples in the empty staves below, then add _repeat_ signs and relevant information to the bottom stave to show that the sequence is performed four times in all **alternating** sides.

**Comment by rsryman** [comment]
Your suggested wording is fine.
