### ISSUE TITLE
Consistency of Dancers' Count placement

### ISSUE THREAD

**Issue by rryman** [rryman/BB3-Worksheets#35]
- [ ] At the end of Book 2 writing worksheets we placed the dancers' count under the legato line.
In the allegro section of Book 3 we seem to consistently place the dancers' counts under the legato line. For some reason, in Book 3 page 45 we have placed the dancers' counts on top of the legato line.
Do you mind for consistency sake if I move the dancers' counts to below the legato line on page 36 of the worksheets? If you agree that it is okay to move them, do we need to say anything about the placement being different than in the ebook? I personally don't think we should mention it, do you?

I checked the RAD Set Exercises and Variations. It seems the placement of the dancers' counts is a choice. There are examples of dancers' counts both above and below the legato line.

**Comment by rsryman** [comment]
No semantic difference, but I think we try to place Dancers' Counts below legato lines unless the lines are so long/low that there isn't room. I agree that there is room to move Dancers' Counts below the legato lines in Book 3 p. 45.

**Comment by rryman** [comment]
Note that Dancer's Counts are placed above the legato lines in Book 3 p. 45. To keep the notation compact they may be placed below the legato lines as shown below.

So why wouldn't we have kept the notation compact in the ebook?

Perhaps:
**Dancers' Counts may be placed either above the legato line (as shown in _Book 3_ p. 45) or under the legato line (as shown below).**

Or 
**Dancers' Counts may be placed either above (as shown in _Book 3_ p. 45) or under the legato line (as shown below).**

**Comment by rsryman** [comment]
I prefer:
Dancers' Counts may be placed either above the legato line (as shown in Book 3 p. 45) or under the legato line (as shown below).
