### ISSUE TITLE
Pages 39 - 42 - combining two different versions on one page

### ISSUE THREAD

**Issue by rryman** [rryman/BB3-Worksheets#36]
Just a thought for your consideration re Grand Battement pp. 39-40 (this would also apply to Adage pp. 41-42). If you agree I'll open a new Issue. The current way allows students to copy both versions of Grand Battement. OR we could put both examples on the same page and give them the option of copying either (but this would cut out a page and cause repagination).

I have redone both these pages (see attached pdfs). Is this what you had in mind?

I will now have to copy and paste each page and move it by two pages forward in the pdf.

It would be helpful if you could look through the Book 4 Worksheets and see if you want to consolidate any of the examples before I start working on them.

[BB3WorksheetsP39.pdf](https://github.com/rryman/BB3-Worksheets/files/2813189/BB3WorksheetsP39.pdf)
[BB3WorksheetsP40.pdf](https://github.com/rryman/BB3-Worksheets/files/2813190/BB3WorksheetsP40.pdf)

**Comment by rsryman** [comment]
That’s why I wanted you to consider the ramifications before making the change. 

Maybe it's not worth changing the pagination if you have to do so much manual adjustment

**Comment by rryman** [comment]
I am spending so much time on these worksheets as it is, we might as well make the changes that seem appropriate as we go. I have made these changes so please look at them and let me know if there are any edits you want made to these two pages.
