### ISSUE TITLE
Page 48 (Book 3 p. 64) - More on Reverse Repeats

### ISSUE THREAD

**Issue by rryman** [rryman/BB3-Worksheets#39]
In BB3Worksheets1FebP48.pdf I had to change the instructions on page 48 as two empty staves were not enough to fit the fully notated Bars 9-16.

- [ ] Rhonda to wordsmith the instructions if necessary.
On stave paper (provided at the end of these worksheets), fully notate the sequence for Bars 9-16 which is Bars 1-8 in reverse on the other side. The starting position will be 5th right foot front facing downstage left. Use the arm and head positions and _direction_ signs that are provided in the “empty” staves after the final repeat sign (see staves 3 and 4).

**Comment by rsryman** [comment]
[See Issue #40], fully notate the sequence for Bars 9-16, which is Bars 1-8 in reverse on the other side. The starting position will be 5th right foot front facing downstage left. Incorporate the arm and head positions and _direction_ signs provided in the “empty” staves after the final _repeat_ sign (see staves 3 and 4).

**Comment by rsryman** [comment]
On stave paper, fully notate the sequence for Bars 9-16, which is Bars 1-8 in reverse on the other side. The starting position will be 5th right foot front facing downstage left. Incorporate the arm and head positions and direction signs provided in the “empty” staves after the final repeat sign (see staves 3 and 4).
