### ISSUE TITLE
Extra pages

### ISSUE THREAD

**Issue by rryman** [rryman/BB3-Worksheets#44]
It just occurred to me that I will be left with two empty pages at the end of the worksheets for Book 3. Given that we ask them to copy all the sequences in the last chapter on staved paper, what do you think about giving them 3 pages of empty staves? This will mean I don't have to copy and paste 60 individual pages of the worksheets into a new Adobe Illustrator file in order to eliminate the last two empty pages.

If you think this is a good idea, then we should change the text of page 3 to something like:
Three printable pages of staves are provided at the end of these worksheets.

If you don't like this idea, no problem. Once I have completed all the edits, I will create a new Adobe Illustrator file. I'll just have to be extra careful not to introduce any errors when I copy and paste!!!

**Comment by rsryman** [comment]
Grr, the domino effect - every solution causes another problem.  It seems redundant to provide 3 pages since they can just print 3 copies of the page. You could just leave two blank pages at the end?

I'm ok with whatever you decide since you're the one who has to do the work.

**Comment by rryman** [comment]
Given we have two extra pages, what do you think about adding Next Steps like we did in the worksheets for Book 2?:

1. Chapter 8 Next Steps
Excerpt from Bluebird Variation (_Book 3_ p. 93. For an explanation of new signs, see p. 91.)
Two staves of notation and two blank staves
Then the next page:
2. Links to all four books on the Apple iBooks Store.
For all four ebooks in this series use the following links:
https://itunes.apple.com/book/id858252059
https://itunes.apple.com/book/id1059244734
https://itunes.apple.com/book/id1192384662
https://itunes.apple.com/book/id1342802435

Then have the stave paper at the end.

**Comment by rsryman** [comment]
A very creative solution. Go for it!
