### ISSUE TITLE
Updated Page 50 text

### ISSUE THREAD

**Issue by rryman** [rryman/BB3-Worksheets#45]
In combining the first two paragraphs I noticed there were 3 "presented" in the one paragraph. I changed the 2nd one to "shown" instead.

I also noticed that landscape format is not hyphenated on the other page and on this page portrait format is not hyphenated so I took out the hyphen.

I also changed "proper spacing" to "suggested spacing" as I think that our spacing tends to be influenced by MacBenesh and is not always "proper".

I also took out ", as a guide" before "You may choose ..."

Here is what the text now looks like. Perhaps you can have a careful read through and see what you think?

Copy each enchaînement from _Book 3_ pp. 67-81 onto stave paper. The landscape format versions presented in _Book 3_ are shown below in portrait format as a guide to suggested spacing and layout. In several of these enchaînements, alternate versions are presented in _Book 3_. Only one version is provided in these worksheets. You may choose to copy one or both versions as needed to gain practice.

Note: The placement of the INTRO end bracket is explained in the left pop-up in _Book 3_ on page 67. _Book 3_ and the corresponding worksheets follow the current practice while _Book 2_ and the corresponding worksheets follow the historical practice. Both usages are acceptable.

**Comment by rryman** [comment]
Here is the updated page. If it is now okay, please close this issue.

[BB3WorksheetsP50.pdf](https://github.com/rryman/BB3-Worksheets/files/2833984/BB3WorksheetsP50.pdf)

**Comment by rsryman** [comment]
All good.
