### ISSUE TITLE
Canan Corrections

### ISSUE THREAD

**Issue by rryman** [rryman/BB3-Worksheets#47]
Canan suggests: p10  "drawing" into or "drawing into" (could be lack of my grammar).

- [x] Rhonda, please confirm that it should remain as "drawing in" in the first paragraph:

Note that a closing 5th position sign is used to indicate a “drawing in” of one foot to the other (as in a rise or press-up action), whereas a static 5th position sign is used to indicate equal action of two feet (as in a relevé action).

- [x] Rhonda, please confirm that I should move the final quote to "drawing **into"** in the following description:

Battements tendus closing/“drawing**” into** 5th on demi-pointes and full pointes

RHONDA's REPLY: We use "drawing in" once in _Book 3_ p. 11, but several times in the Worksheets: pp.  6(x2), 8, 10, and inconsistently on p.10: “drawing” into. 
OPTION 1 (preferred): change the inconsistency on p. 10: “drawing” into 5th -> “drawing in" to 5th 
OPTION 2: take out all the double quotes in the 5 instances of "drawing in" in the Worksheets

**Comment by rryman** [comment]
Rhonda, do you understand this comment:
p 18 Italian or (Italian), also on pages 19, 21, 39, 40, 42, 43, 44.

Do you think that Canan is suggesting that we use brackets around Italian, English, and Russian on these pages like we did in previous pages (11, 14, 16, etc.)? Or is she suggesting something else that I am not seeing?

Let me know if you are also unclear what Canan is suggesting and I will email her to clarify.

**Comment by rryman** [comment]
p60 The repeat signs should be dotted. Should there be a pulse beat at count 3 on the 5th bar ?

I corrected the repeat signs.

Should I add a pulse beat of count 3 of the first bar of the second stave and the first beat of the last bar, and say something about them being omitted in the ebook?

(See Parker text page 54.)

**Comment by rryman** [comment]
Here is the updated version. Did you want to check the updates on pages 5, 10, and 60 (see latest email to Canan) before I upload these worksheets to the server?

[B4B_Book3_Worksheets.pdf](https://github.com/rryman/BB3-Worksheets/files/2866403/B4B_Book3_Worksheets.pdf)

**Comment by rsryman** [comment]
All checked -- good to go!
