### ISSUE TITLE
Proofreading BB3 Worksheets - Overall Comments

### ISSUE THREAD

**Issue by rryman** [rryman/BB3-Worksheets#6]

**Comment by rsryman** [comment]
Re italics: I did a global search of two relevant terms from BB4 Worksheets ItalicizationOfTerms #3:

location sign: N/A
locomotion line: N/A
stage plan: N/A
travel sign: N/A
- [√ ] movement line: p. 12 (x3)
- [√ ] repeat sign; p. 24, p. 50

**Comment by rsryman** [comment]
Re capitalization as on p. 10: Retiré devant/Pirouette position; Retiré; High retiré derrière

I understand you want me to **capitalize** the first letter in the title and also use a **forward slash** to separate alternate names. 

Please confirm that this is what you want before I start going through all from the beginning.
