### ISSUE TITLE
Proofreading - BB3 Worksheets - p. 10

### ISSUE THREAD

**Issue by rryman** [rryman/BB3-Worksheets#9]
I think it would be helpful to have an extra stave with greyed out retire signs on this page.
There is room without bumping to another page.

The instructions could say:
Start by tracing the grey notation (the Benesh signs only, not the stave lines or bar lines), then recopy each position into the empty frames. Remember to drawing the basic contact sign first, placing it carefully in relation to the knee line and the centre line of the frame. Then add the qualifying line or open dot.

**Comment by rsryman** [comment]
Done. Also I caught a typo: Remember to **draw** the basic _contact_ sign….
